### ISSUE TITLE
Add max xp graphic

### ISSUE THREAD

**Issue by AM-Mikey** [AM-Mikey/Laputa#135]

**Comment by AsperDev1** [comment]
![obraz](https://user-images.githubusercontent.com/86064084/124879698-c5843e00-dfcd-11eb-8570-b5c516c7813f.png)
![obraz](https://user-images.githubusercontent.com/86064084/124879729-d1700000-dfcd-11eb-9913-b83ad282a81e.png)

**Comment by AM-Mikey** [comment]
it displays, but I don't have an original graphic for it yet. Changed title

**Comment by AsperDev1** [comment]
![obraz](https://user-images.githubusercontent.com/86064084/126033009-6ed15ea0-ffbd-4d28-b55f-fdefbab2ed62.png)
